apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot-bff-deployment
  namespace: mfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pinot-bff
  template:
    metadata:
      labels:
        app: pinot-bff
    spec:
      containers:
      - name: pinot-bff
        image: porpoiseltd/pinot-bff:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pinot-bff-service
  namespace: mfe
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: pinot-bff
  ports:
  - name : default
    port: 8080
    targetPort: 8080