run: build
	source ./build.sh && run
build: 
	source ./build.sh && build
buildLocal: 
	source ./build.sh && buildLocally
push: build
	source ./build.sh && push
test:
	source ./build.sh && testRegisterLocal && testHeartbeatLocal