run: build
	source ./build.sh && run
runLocal:
	source ./build.sh && runLocal
build: 
	source ./build.sh && build
push: build
	source ./build.sh && push
installArgo:
	source ./build.sh && installArgo
