runDocker: buildDocker
	source ./build.sh && runDocker
run:
	source ./build.sh && run
buildDocker: 
	source ./build.sh && buildDocker
push: buildDocker
	source ./build.sh && push
installArgo:
	source ./build.sh && installArgo
test:
	source ./build.sh && test